version: '2'

services:

  telegraf:
    image: telegraf:1.5.3
    container_name: telegraf
    hostname: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf.d/:/etc/telegraf/telegraf.d/:ro
    links:
      - influxdb
    command: --config-directory /etc/telegraf/telegraf.d
    ports:
      - "0.0.0.0:8186:8186"

  influxdb:
    image: influxdb:1.5.2
    container_name: influxdb
    environment:
      HOSTNAME: influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf:1.4.4.1
    hostname: chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - "0.0.0.0:18888:8888"
    links:
      - influxdb
    depends_on:
      - telegraf
      - influxdb

